providers = ["python", "node"]

[variables]
PYTHON_VERSION = "3.11"
NODE_VERSION = "20"
[phases.install-backend]
base_directory = "backend"
cmds = [
  "pip install -r requirements.txt"
]

[phases.install-frontend]
base_directory = "frontend"
cmds = [
  "npm ci"
]

[phases.build-frontend]
base_directory = "frontend"
cmds = [
  "npm run build"
]

[start]
cmd = "uvicorn backend.main:app --host 0.0.0.0 --port ${PORT:-8000}"

