providers = ["python", "node"]

[variables]
PYTHON_VERSION = "3.11"
NODE_VERSION = "20"

[phases.install]
cmds = [
  "pip install -r backend/requirements.txt",
  "npm --prefix frontend ci"
]

[phases.build]
cmds = [
  "npm --prefix frontend run build"
]

[start]
cmd = "uvicorn backend.main:app --host 0.0.0.0 --port $PORT"

