services:
  - type: web
    name: sage-video-downloader
    env: docker
    plan: free
    autoDeploy: true
    dockerfilePath: Dockerfile
    healthCheckPath: /healthz
    envVars:
      - key: COOKIES_B64
        sync: false
      - key: PROXY_URL
        sync: false
