- type: web
  name: sage-backend
  env: python
  rootDir: backend
  buildCommand: pip install -r requirements.txt
  startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
  healthCheckPath: /healthz
  envVars:
    - key: PYTHON_VERSION
      value: 3.11
  disk:
    name: downloads
    mountPath: /opt/render/project/src/downloads
    sizeGB: 2

- type: static_site
  name: sage-frontend
  rootDir: frontend
  buildCommand: npm ci && npm run build
  publishPath: out
  envVars:
    - key: NEXT_PUBLIC_API_BASE
      fromService:
        type: web
        name: sage-backend
        property: url
    - key: NODE_VERSION
      value: 20

